// resources/js/Pages/Organizations/CreateOrganizationForm.jsx
import * as React from 'react';
import classnames from 'classnames';
import { usePage } from '@inertiajs/inertia-react';
import FormSection from '@/Jetstream/FormSection';
import Label from '@/Jetstream/Label';
import Input from '@/Jetstream/Input';
import InputError from '@/Jetstream/InputError';
import Button from '@/Jetstream/Button';
import useForm from '@/hooks/useForm';

const CreateOrganizationForm = () => {
  const { user, errors } = usePage().props;
  const { status, submit, useField } = useForm({
    name: '',
  });
  const isProcessing = status === 'processing';
  const [name, setName] = useField('name');

  const createOrganization = () => {
    submit(new Promise((resolve) => {
      Inertia.post(route('organizations.store'), data, {
        errorBag: 'createOrganization',
        preserveScroll: true,
        onFinish: () => {
          resolve();
        },
      });
    }));
  };

  return (
    <FormSection
      onSubmit={createOrganization}
      title="Organization Details"
      description="Create a new organization to collaborate with others on projects."
      form={(
        <>
          <div className="col-span-6">
            <Label value="Organization Owner" />

            <div className="flex items-center mt-2">
              <img className="w-12 h-12 rounded-full object-cover" src={user.profile_photo_url} alt="" />

              <div className="ml-4 leading-tight">
                <div>{user.name}</div>
                <div className="text-gray-700 text-sm">{user.email}</div>
              </div>
            </div>
          </div>

          <div className="col-span-6 sm:col-span-4">
            <Label htmlFor="name" value="Organization Name" />
            <Input
              id="name"
              type="text"
              className="mt-1 block w-full"
              value={name}
              onChange={(value) => setName(value)}
              autoFocus
            />
            <InputError message={errors?.createOrganization?.name} className="mt-2" />
          </div>
        </>
      )}
      actions={(
        <Button
          className={classnames({ 'opacity-25': isProcessing })}
          disabled={isProcessing}
        >
          Create
        </Button>
      )}
    />
  );
};

export default CreateOrganizationForm;

// resources/js/Pages/Organizations/CreateOrganizationForm.vue
<template>
    <jet-form-section @submitted="createOrganization">
        <template #title>
            Organization Details
        </template>

        <template #description>
            Create a new organization to collaborate with others on projects.
        </template>

        <template #form>
            <div class="col-span-6">
                <jet-label value="Organization Owner" />

                <div class="flex items-center mt-2">
                    <img class="w-12 h-12 rounded-full object-cover" :src="$page.props.user.profile_photo_url" :alt="$page.props.user.name">

                    <div class="ml-4 leading-tight">
                        <div>{{ $page.props.user.name }}</div>
                        <div class="text-gray-700 text-sm">{{ $page.props.user.email }}</div>
                    </div>
                </div>
            </div>

            <div class="col-span-6 sm:col-span-4">
                <jet-label for="name" value="Organization Name" />
                <jet-input id="name" type="text" class="mt-1 block w-full" v-model="form.name" autofocus />
                <jet-input-error :message="form.errors.name" class="mt-2" />
            </div>
        </template>

        <template #actions>
            <jet-button :class="{ 'opacity-25': form.processing }" :disabled="form.processing">
                Create
            </jet-button>
        </template>
    </jet-form-section>
</template>

<script>
    import JetButton from '@/Jetstream/Button'
    import JetFormSection from '@/Jetstream/FormSection'
    import JetInput from '@/Jetstream/Input'
    import JetInputError from '@/Jetstream/InputError'
    import JetLabel from '@/Jetstream/Label'

    export default {
        components: {
            JetButton,
            JetFormSection,
            JetInput,
            JetInputError,
            JetLabel,
        },

        data() {
            return {
                form: this.$inertia.form({
                    name: '',
                })
            }
        },

        methods: {
            createOrganization() {
                this.form.post(route('organizations.store'), {
                    errorBag: 'createOrganization',
                    preserveScroll: true
                });
            },
        },
    }
</script>
