// resources/js/Pages/Organizations/Create.vue
<template>
    <app-layout>
        <template #header>
            <h2 class="font-semibold text-xl text-gray-800 leading-tight">
                Create Organization
            </h2>
        </template>

        <div>
            <div class="max-w-7xl mx-auto py-10 sm:px-6 lg:px-8">
                <create-organization-form />
            </div>
        </div>
    </app-layout>
</template>

<script>
    import AppLayout from '@/Layouts/AppLayout'
    import CreateOrganizationForm from './CreateOrganizationForm'

    export default {
        components: {
            AppLayout,
            CreateOrganizationForm,
        },
    }
</script>

// resources/js/Pages/Organizations/Create.jsx
import * as React from 'react';
import AppLayout from '@/Layouts/AppLayout';
import CreateOrganizationForm from './CreateOrganizationForm';

const Create = () => {
  return (
    <AppLayout header={(
      <h2 className="font-semibold text-xl text-gray-800 leading-tight">
        Create Organization
      </h2>
    )}>
      <div>
        <div className="max-w-7xl mx-auto py-10 sm:px-6 lg:px-8">
          <CreateOrganizationForm />
        </div>
      </div>
    </AppLayout>
  );
};

export default Create;
