// resources/js/Layouts/AppLayout.jsx
import * as React from 'react';
import PropTypes, { node } from 'prop-types';
import classnames from 'classnames';
import { Inertia } from '@inertiajs/inertia';
import { InertiaLink, usePage } from '@inertiajs/inertia-react';

import Banner from '@/Jetstream/Banner';
import ApplicationMark from '@/Jetstream/ApplicationMark';
import NavLink from '@/Jetstream/NavLink';
import ResponsiveNavLink from '@/Jetstream/ResponsiveNavLink';
import Dropdown from '@/Jetstream/Dropdown';
import DropdownLink from '@/Jetstream/DropdownLink';
import withPreventDefault from '@/util/withPreventDefault';

const AppLayout = ({ header = '', children }) => {
  const [showingNavigationDropdown, setShowingNavigationDropdown] = React.useState(false);

  const { jetstream, user } = usePage().props;

  const switchToOrganization = (organization) => {
    Inertia.put(route('current-organization.update'), {
      'organization_id': organization.id
    }, {
      preserveState: false
    })
  };

  const logout = () => {
    Inertia.post(route('logout'));
  };

  return (
    <div>
      <Banner />

      <div className="min-h-screen bg-gray-100">
        <nav className="bg-white border-b border-gray-100">
          {/* Primary Navigation Menu */}
          <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
            <div className="flex justify-between h-16">
              <div className="flex">
                {/* Logo */}
                <div className="flex-shrink-0 flex items-center">
                  <InertiaLink href={route('dashboard')}>
                    <ApplicationMark className="block h-9 w-auto" />
                  </InertiaLink>
                </div>

                {/* Navigation Links */}
                <div className="hidden space-x-8 sm:-my-px sm:ml-10 sm:flex">
                  <NavLink href={route('dashboard')} active={route().current('dashboard')}>
                    Dashboard
                  </NavLink>
                </div>
              </div>

              <div className="hidden sm:flex sm:items-center sm:ml-6">
                <div className="ml-3 relative">
                  {/* Organizations Dropdown */}
                  {!!jetstream.hasOrganizationFeatures ? (
                    <Dropdown
                      align="right"
                      width="60"
                      trigger={(
                        <span className="inline-flex rounded-md">
                          <button type="button" className="inline-flex items-center px-3 py-2 border border-transparent text-sm leading-4 font-medium rounded-md text-gray-500 bg-white hover:bg-gray-50 hover:text-gray-700 focus:outline-none focus:bg-gray-50 active:bg-gray-50 transition ease-in-out duration-150">
                            {user.current_organization.name}

                            <svg className="ml-2 -mr-0.5 h-4 w-4" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor">
                              <path fillRule="evenodd" d="M10 3a1 1 0 01.707.293l3 3a1 1 0 01-1.414 1.414L10 5.414 7.707 7.707a1 1 0 01-1.414-1.414l3-3A1 1 0 0110 3zm-3.707 9.293a1 1 0 011.414 0L10 14.586l2.293-2.293a1 1 0 011.414 1.414l-3 3a1 1 0 01-1.414 0l-3-3a1 1 0 010-1.414z" clipRule="evenodd" />
                            </svg>
                          </button>
                        </span>
                      )}
                      content={(
                        <div className="w-60">
                          {/* Organization Management */}
                          {jetstream.hasOrganizationFeatures ? (
                            <>
                              <div className="block px-4 py-2 text-xs text-gray-400">
                                Manage Organization
                              </div>

                              {/* Organization Settings */}
                              <DropdownLink href={route('organizations.show', user.current_organization)}>
                                Organization Settings
                              </DropdownLink>

                              {jetstream.canCreateOrganizations ? (
                                <DropdownLink href={route('organizations.create')}>
                                  Create New Organization
                                </DropdownLink>
                              ) : null}

                              <div className="border-t border-gray-100"></div>

                              {/* Organization Switcher */}
                              <div className="block px-4 py-2 text-xs text-gray-400">
                                Switch Organizations
                              </div>

                              {user.all_organizations.map((organization) => (
                                <form key={organization.id} onSubmit={withPreventDefault(() => switchToOrganization(organization))}>
                                  <DropdownLink as="button">
                                    <div className="flex items-center">
                                      {organization.id == user.current_organization_id ? (
                                        <svg className="mr-2 h-5 w-5 text-green-400" fill="none" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" stroke="currentColor" viewBox="0 0 24 24"><path d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z"></path></svg>
                                      ) : null}
                                      <div>{organization.name}</div>
                                    </div>
                                  </DropdownLink>
                                </form>
                              ))}
                            </>
                          ) : null}
                        </div>
                      )}
                    />
                  ) : null}
                </div>

                {/* Settings Dropdown */}
                <div className="ml-3 relative">
                  <Dropdown
                    align="right"
                    width="48"
                    trigger={(
                      <>
                        {jetstream.managesProfilePhotos ? (
                          <button className="flex text-sm border-2 border-transparent rounded-full focus:outline-none focus:border-gray-300 transition duration-150 ease-in-out">
                            <img className="h-8 w-8 rounded-full object-cover" src={user.profile_photo_url} alt={user.name} />
                          </button>
                        ) : (
                          <span className="inline-flex rounded-md">
                            <button type="button" className="inline-flex items-center px-3 py-2 border border-transparent text-sm leading-4 font-medium rounded-md text-gray-500 bg-white hover:text-gray-700 focus:outline-none transition ease-in-out duration-150">
                              {user.name}

                              <svg className="ml-2 -mr-0.5 h-4 w-4" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor">
                                <path fillRule="evenodd" d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z" clipRule="evenodd" />
                              </svg>
                            </button>
                          </span>
                        )}
                      </>
                    )}
                    content={(
                      <>
                        {/* Account Management */}
                        <div className="block px-4 py-2 text-xs text-gray-400">
                          Manage Account
                        </div>

                        <DropdownLink href={route('profile.show')}>
                          Profile
                        </DropdownLink>

                        {jetstream.hasApiFeatures ? (
                          <DropdownLink href={route('api-tokens.index')}>
                            API Tokens
                          </DropdownLink>
                        ) : null}

                        <div className="border-t border-gray-100"></div>

                        {/* Authentication */}
                        <form onSubmit={withPreventDefault(logout)}>
                          <DropdownLink as="button">
                            Log Out
                          </DropdownLink>
                        </form>
                      </>
                    )}
                  />
                </div>
              </div>

              {/* Hamburger */}
              <div className="-mr-2 flex items-center sm:hidden">
                <button onClick={() => setShowingNavigationDropdown((s) => !s)} className="inline-flex items-center justify-center p-2 rounded-md text-gray-400 hover:text-gray-500 hover:bg-gray-100 focus:outline-none focus:bg-gray-100 focus:text-gray-500 transition duration-150 ease-in-out">
                  <svg className="h-6 w-6" stroke="currentColor" fill="none" viewBox="0 0 24 24">
                    <path className={classnames({ 'hidden': showingNavigationDropdown, 'inline-flex': !showingNavigationDropdown })} strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M4 6h16M4 12h16M4 18h16" />
                    <path className={classnames({ 'hidden': !showingNavigationDropdown, 'inline-flex': showingNavigationDropdown })} strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M6 18L18 6M6 6l12 12" />
                  </svg>
                </button>
              </div>
            </div>
          </div>

          {/* Responsive Navigation Menu */}
          <div className={classnames({ 'block': showingNavigationDropdown, 'hidden': !showingNavigationDropdown }, 'sm:hidden')}>
            <div className="pt-2 pb-3 space-y-1">
              <ResponsiveNavLink href={route('dashboard')} active={route().current('dashboard')}>
                Dashboard
              </ResponsiveNavLink>
            </div>

            {/* <!--Responsive Settings Options--> */ }
            <div className="pt-4 pb-1 border-t border-gray-200">
              <div className="flex items-center px-4">
                {jetstream.managesProfilePhotos ? (
                  <div className="flex-shrink-0 mr-3">
                    <img className="h-10 w-10 rounded-full object-cover" src={user.profile_photo_url} alt={user.name} />
                  </div>
                ) : null}

                <div>
                  <div className="font-medium text-base text-gray-800">{user.name}</div>
                  <div className="font-medium text-sm text-gray-500">{user.email}</div>
                </div>
              </div>

              <div className="mt-3 space-y-1">
                <ResponsiveNavLink href={route('profile.show')} active={route().current('profile.show')}>
                  Profile
                </ResponsiveNavLink>

                {jetstream.hasApiFeatures ? (
                  <ResponsiveNavLink href={route('api-tokens.index')} active={route().current('api-tokens.index')}>
                    API Tokens
                  </ResponsiveNavLink>
                ) : null}

                {/* Authentication */}
                <form method="POST" onSubmit={withPreventDefault(logout)}>
                  <ResponsiveNavLink as="button">
                    Log Out
                  </ResponsiveNavLink>
                </form>

                {/* Organization Management */}
                {jetstream.hasOrganizationFeatures ? (
                  <>
                    <div className="border-t border-gray-200"></div>

                    <div className="block px-4 py-2 text-xs text-gray-400">
                      Manage Organization
                    </div>

                    {/* Organization Settings */}
                    <ResponsiveNavLink href={route('organizations.show', user.current_organization)} active={route().current('organizations.show')}>
                      Organization Settings
                    </ResponsiveNavLink>

                    <ResponsiveNavLink href={route('organizations.create')} active={route().current('organizations.create')}>
                      Create New Organization
                    </ResponsiveNavLink>

                    <div className="border-t border-gray-200"></div>

                    {/* Organization Switcher */}
                    <div className="block px-4 py-2 text-xs text-gray-400">
                      Switch Organizations
                    </div>

                    {user.all_organizations.map((organization) => (
                      <form onSubmit={withPreventDefault(() => switchToOrganization(organization))} key={organization.id}>
                        <ResponsiveNavLink as="button">
                          <div className="flex items-center">
                            {organization.id === user.current_organization_id ? (
                              <svg className="mr-2 h-5 w-5 text-green-400" fill="none" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" stroke="currentColor" viewBox="0 0 24 24"><path d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z"></path></svg>
                            ) : null}
                            <div>{organization.name}</div>
                          </div>
                        </ResponsiveNavLink>
                      </form>
                    ))}
                  </>
                ) : null}
              </div>
            </div>
          </div>
        </nav>

        {/* Page Heading */}
        {!!header ? (
          <header className="bg-white shadow">
            <div className="max-w-7xl mx-auto py-6 px-4 sm:px-6 lg:px-8">
              {header}
            </div>
          </header>
        ) : null}

        {/* Page Content */}
        <main>
          {children}
        </main>
      </div>
    </div>
  );
};

AppLayout.propTypes = {
  header: node,
  children: node.isRequired,
};

export default AppLayout;

// resources/js/Layouts/AppLayout.vue
<template>
    <div>
        <jet-banner />

        <div class="min-h-screen bg-gray-100">
            <nav class="bg-white border-b border-gray-100">
                <!-- Primary Navigation Menu -->
                <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
                    <div class="flex justify-between h-16">
                        <div class="flex">
                            <!-- Logo -->
                            <div class="flex-shrink-0 flex items-center">
                                <inertia-link :href="route('dashboard')">
                                    <jet-application-mark class="block h-9 w-auto" />
                                </inertia-link>
                            </div>

                            <!-- Navigation Links -->
                            <div class="hidden space-x-8 sm:-my-px sm:ml-10 sm:flex">
                                <jet-nav-link :href="route('dashboard')" :active="route().current('dashboard')">
                                    Dashboard
                                </jet-nav-link>
                            </div>
                        </div>

                        <div class="hidden sm:flex sm:items-center sm:ml-6">
                            <div class="ml-3 relative">
                                <!-- Organizations Dropdown -->
                                <jet-dropdown align="right" width="60" v-if="$page.props.jetstream.hasOrganizationFeatures">
                                    <template #trigger>
                                        <span class="inline-flex rounded-md">
                                            <button type="button" class="inline-flex items-center px-3 py-2 border border-transparent text-sm leading-4 font-medium rounded-md text-gray-500 bg-white hover:bg-gray-50 hover:text-gray-700 focus:outline-none focus:bg-gray-50 active:bg-gray-50 transition ease-in-out duration-150">
                                                {{ $page.props.user.current_organization.name }}

                                                <svg class="ml-2 -mr-0.5 h-4 w-4" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor">
                                                    <path fill-rule="evenodd" d="M10 3a1 1 0 01.707.293l3 3a1 1 0 01-1.414 1.414L10 5.414 7.707 7.707a1 1 0 01-1.414-1.414l3-3A1 1 0 0110 3zm-3.707 9.293a1 1 0 011.414 0L10 14.586l2.293-2.293a1 1 0 011.414 1.414l-3 3a1 1 0 01-1.414 0l-3-3a1 1 0 010-1.414z" clip-rule="evenodd" />
                                                </svg>
                                            </button>
                                        </span>
                                    </template>

                                    <template #content>
                                        <div class="w-60">
                                            <!-- Organization Management -->
                                            <template v-if="$page.props.jetstream.hasOrganizationFeatures">
                                                <div class="block px-4 py-2 text-xs text-gray-400">
                                                    Manage Organization
                                                </div>

                                                <!-- Organization Settings -->
                                                <jet-dropdown-link :href="route('organizations.show', $page.props.user.current_organization)">
                                                    Organization Settings
                                                </jet-dropdown-link>

                                                <jet-dropdown-link :href="route('organizations.create')" v-if="$page.props.jetstream.canCreateOrganizations">
                                                    Create New Organization
                                                </jet-dropdown-link>

                                                <div class="border-t border-gray-100"></div>

                                                <!-- Organization Switcher -->
                                                <div class="block px-4 py-2 text-xs text-gray-400">
                                                    Switch Organizations
                                                </div>

                                                <template v-for="organization in $page.props.user.all_organizations" :key="organization.id">
                                                    <form @submit.prevent="switchToOrganization(organization)">
                                                        <jet-dropdown-link as="button">
                                                            <div class="flex items-center">
                                                                <svg v-if="organization.id == $page.props.user.current_organization_id" class="mr-2 h-5 w-5 text-green-400" fill="none" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" stroke="currentColor" viewBox="0 0 24 24"><path d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z"></path></svg>
                                                                <div>{{ organization.name }}</div>
                                                            </div>
                                                        </jet-dropdown-link>
                                                    </form>
                                                </template>
                                            </template>
                                        </div>
                                    </template>
                                </jet-dropdown>
                            </div>

                            <!-- Settings Dropdown -->
                            <div class="ml-3 relative">
                                <jet-dropdown align="right" width="48">
                                    <template #trigger>
                                        <button v-if="$page.props.jetstream.managesProfilePhotos" class="flex text-sm border-2 border-transparent rounded-full focus:outline-none focus:border-gray-300 transition duration-150 ease-in-out">
                                            <img class="h-8 w-8 rounded-full object-cover" :src="$page.props.user.profile_photo_url" :alt="$page.props.user.name" />
                                        </button>

                                        <span v-else class="inline-flex rounded-md">
                                            <button type="button" class="inline-flex items-center px-3 py-2 border border-transparent text-sm leading-4 font-medium rounded-md text-gray-500 bg-white hover:text-gray-700 focus:outline-none transition ease-in-out duration-150">
                                                {{ $page.props.user.name }}

                                                <svg class="ml-2 -mr-0.5 h-4 w-4" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor">
                                                    <path fill-rule="evenodd" d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z" clip-rule="evenodd" />
                                                </svg>
                                            </button>
                                        </span>
                                    </template>

                                    <template #content>
                                        <!-- Account Management -->
                                        <div class="block px-4 py-2 text-xs text-gray-400">
                                            Manage Account
                                        </div>

                                        <jet-dropdown-link :href="route('profile.show')">
                                            Profile
                                        </jet-dropdown-link>

                                        <jet-dropdown-link :href="route('api-tokens.index')" v-if="$page.props.jetstream.hasApiFeatures">
                                            API Tokens
                                        </jet-dropdown-link>

                                        <div class="border-t border-gray-100"></div>

                                        <!-- Authentication -->
                                        <form @submit.prevent="logout">
                                            <jet-dropdown-link as="button">
                                                Log Out
                                            </jet-dropdown-link>
                                        </form>
                                    </template>
                                </jet-dropdown>
                            </div>
                        </div>

                        <!-- Hamburger -->
                        <div class="-mr-2 flex items-center sm:hidden">
                            <button @click="showingNavigationDropdown = ! showingNavigationDropdown" class="inline-flex items-center justify-center p-2 rounded-md text-gray-400 hover:text-gray-500 hover:bg-gray-100 focus:outline-none focus:bg-gray-100 focus:text-gray-500 transition duration-150 ease-in-out">
                                <svg class="h-6 w-6" stroke="currentColor" fill="none" viewBox="0 0 24 24">
                                    <path :class="{'hidden': showingNavigationDropdown, 'inline-flex': ! showingNavigationDropdown }" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16" />
                                    <path :class="{'hidden': ! showingNavigationDropdown, 'inline-flex': showingNavigationDropdown }" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
                                </svg>
                            </button>
                        </div>
                    </div>
                </div>

                <!-- Responsive Navigation Menu -->
                <div :class="{'block': showingNavigationDropdown, 'hidden': ! showingNavigationDropdown}" class="sm:hidden">
                    <div class="pt-2 pb-3 space-y-1">
                        <jet-responsive-nav-link :href="route('dashboard')" :active="route().current('dashboard')">
                            Dashboard
                        </jet-responsive-nav-link>
                    </div>

                    <!-- Responsive Settings Options -->
                    <div class="pt-4 pb-1 border-t border-gray-200">
                        <div class="flex items-center px-4">
                            <div v-if="$page.props.jetstream.managesProfilePhotos" class="flex-shrink-0 mr-3" >
                                <img class="h-10 w-10 rounded-full object-cover" :src="$page.props.user.profile_photo_url" :alt="$page.props.user.name" />
                            </div>

                            <div>
                                <div class="font-medium text-base text-gray-800">{{ $page.props.user.name }}</div>
                                <div class="font-medium text-sm text-gray-500">{{ $page.props.user.email }}</div>
                            </div>
                        </div>

                        <div class="mt-3 space-y-1">
                            <jet-responsive-nav-link :href="route('profile.show')" :active="route().current('profile.show')">
                                Profile
                            </jet-responsive-nav-link>

                            <jet-responsive-nav-link :href="route('api-tokens.index')" :active="route().current('api-tokens.index')" v-if="$page.props.jetstream.hasApiFeatures">
                                API Tokens
                            </jet-responsive-nav-link>

                            <!-- Authentication -->
                            <form method="POST" @submit.prevent="logout">
                                <jet-responsive-nav-link as="button">
                                    Log Out
                                </jet-responsive-nav-link>
                            </form>

                            <!-- Organization Management -->
                            <template v-if="$page.props.jetstream.hasOrganizationFeatures">
                                <div class="border-t border-gray-200"></div>

                                <div class="block px-4 py-2 text-xs text-gray-400">
                                    Manage Organization
                                </div>

                                <!-- Organization Settings -->
                                <jet-responsive-nav-link :href="route('organizations.show', $page.props.user.current_organization)" :active="route().current('organizations.show')">
                                    Organization Settings
                                </jet-responsive-nav-link>

                                <jet-responsive-nav-link :href="route('organizations.create')" :active="route().current('organizations.create')">
                                    Create New Organization
                                </jet-responsive-nav-link>

                                <div class="border-t border-gray-200"></div>

                                <!-- Organization Switcher -->
                                <div class="block px-4 py-2 text-xs text-gray-400">
                                    Switch Organizations
                                </div>

                                <template v-for="organization in $page.props.user.all_organizations" :key="organization.id">
                                    <form @submit.prevent="switchToOrganization(organization)">
                                        <jet-responsive-nav-link as="button">
                                            <div class="flex items-center">
                                                <svg v-if="organization.id == $page.props.user.current_organization_id" class="mr-2 h-5 w-5 text-green-400" fill="none" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" stroke="currentColor" viewBox="0 0 24 24"><path d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z"></path></svg>
                                                <div>{{ organization.name }}</div>
                                            </div>
                                        </jet-responsive-nav-link>
                                    </form>
                                </template>
                            </template>
                        </div>
                    </div>
                </div>
            </nav>

            <!-- Page Heading -->
            <header class="bg-white shadow" v-if="$slots.header">
                <div class="max-w-7xl mx-auto py-6 px-4 sm:px-6 lg:px-8">
                    <slot name="header"></slot>
                </div>
            </header>

            <!-- Page Content -->
            <main>
                <slot></slot>
            </main>
        </div>
    </div>
</template>

<script>
    import JetApplicationMark from '@/Jetstream/ApplicationMark'
    import JetBanner from '@/Jetstream/Banner'
    import JetDropdown from '@/Jetstream/Dropdown'
    import JetDropdownLink from '@/Jetstream/DropdownLink'
    import JetNavLink from '@/Jetstream/NavLink'
    import JetResponsiveNavLink from '@/Jetstream/ResponsiveNavLink'

    export default {
        components: {
            JetApplicationMark,
            JetBanner,
            JetDropdown,
            JetDropdownLink,
            JetNavLink,
            JetResponsiveNavLink,
        },

        data() {
            return {
                showingNavigationDropdown: false,
            }
        },

        methods: {
            switchToOrganization(organization) {
                this.$inertia.put(route('current-organization.update'), {
                    'organization_id': organization.id
                }, {
                    preserveState: false
                })
            },

            logout() {
                this.$inertia.post(route('logout'));
            },
        }
    }
</script>
